services:
  - type: web
    name: finance-planer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
